# Generated by Django 4.1.7 on 2023-02-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApp', '0002_remove_order_product_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='ProductApp.ProductOrder', to='ProductApp.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(through='ProductApp.ProductCategory', to='ProductApp.category'),
        ),
    ]
